Controllers/ContractController.cs
using LAB.IService;
using LAB.Models;
using LAB.Service;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace LAB.Controllers
{
	public class ContractController : Controller
	{
		IUnitOfWork unitOfWork;
		public ContractController(IUnitOfWork unitOfWork)
		{
			this.unitOfWork = unitOfWork;
		}


		public ActionResult Add_Contract(int vendor_id)
		{
			ViewBag.vendor_id = vendor_id;
			var model = unitOfWork._Context.VendorContractTypes.ToList();
			return View(model);
		}


		[HttpPost]
		public ActionResult Add(VendorContract contract)
		{
			var listContract=unitOfWork._Context.VendorContracts.Where(x => x.VendorId == contract.VendorId).ToList();
			foreach (var item in listContract)
			{
				if (item.EndDate > contract.StartDate)
				{
					item.EndDate = contract.StartDate.AddDays(-1);
				}
			}
			unitOfWork.ContractService.Add(contract);
			unitOfWork.Save();
			return RedirectToAction(controllerName:"Vendor" , actionName:"Index");
		}



		[HttpGet]
		public ActionResult Edit(int id)
		{
			VendorContract contract = unitOfWork.ContractService.GetById(id);
			contract.LastUpdateBy = "eman";
			contract.LastUpdateFrom = "1";
			contract.LastUpdateDate = DateTime.Now;
			return View(contract);
		}


		[HttpPost]
		public ActionResult Edit(VendorContract contract)
		{
			unitOfWork.ContractService.Update(contract);
			unitOfWork.Save();
			return RedirectToAction(controllerName: "Vendor", actionName: "Index");
		}





		public IActionResult Index()
		{
			return View();
		}
	}
}

Views/Contract/Add_Contract.cshtml
@model IEnumerable<LAB.Models.VendorContractType>;
@{
    ViewData["Title"] = "Add_Contract";
    Layout = null;
}

<form class="form fv-plugins-bootstrap5 fv-plugins-framework" method="post" asp-controller="Contract" asp-action="Add" id="kt_modal_add_customer_form">

	<!--begin::hidden info-->
	<input type="hidden" class="form-control form-control-solid" placeholder="" name="VendorId" value="@ViewBag.vendor_id">
	<!--end::hidden info-->
	<!--begin::Modal header-->
	<div class="modal-header" id="kt_modal_add_customer_header">
		<!--begin::Modal title-->
		<h2 class="fw-bold">Add a Contract</h2>
		<!--end::Modal title-->
		<!--begin::Close-->
		<div id="kt_modal_add_customer_close" class="btn btn-icon btn-sm btn-active-icon-primary">
			<!--begin::Svg Icon | path: icons/duotune/arrows/arr061.svg-->
			<span class="svg-icon svg-icon-1">
				<svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
					<rect opacity="0.5" x="6" y="17.3137" width="16" height="2" rx="1" transform="rotate(-45 6 17.3137)" fill="currentColor"></rect>
					<rect x="7.41422" y="6" width="16" height="2" rx="1" transform="rotate(45 7.41422 6)" fill="currentColor"></rect>
				</svg>
			</span>
			<!--end::Svg Icon-->
		</div>
		<!--end::Close-->
	</div>
	<!--end::Modal header-->
	<!--begin::Modal body-->
	<div class="modal-body py-10 px-lg-17">
		<!--begin::Scroll-->
		<div class="scroll-y me-n7 pe-7" id="kt_modal_add_customer_scroll" data-kt-scroll="true" data-kt-scroll-activate="{default: false, lg: true}" data-kt-scroll-max-height="auto" data-kt-scroll-dependencies="#kt_modal_add_customer_header" data-kt-scroll-wrappers="#kt_modal_add_customer_scroll" data-kt-scroll-offset="300px" style="max-height: 490px;">
			<!--begin::Input group-->
			<div class="fv-row mb-7 fv-plugins-icon-container">
				<!--begin::Label-->
				<label class="required fs-6 fw-semibold mb-2">Contract Name</label>
				<!--end::Label-->
				<!--begin::Input-->
				<input type="text" class="form-control form-control-solid" placeholder="" name="ContractName" value="">
				<!--end::Input-->
				<div class="fv-plugins-message-container invalid-feedback"></div>
			</div>
			<!--end::Input group-->
			<!--begin::Input group-->
			<div class="row">
				<div class="fv-row mb-7 fv-plugins-icon-container col-6">
					<!--begin::Label-->
					<label class="required fs-6 fw-semibold mb-2">StartDate</label>
					<!--end::Label-->
					<!--begin::Input-->
					<input type="date" class="form-control form-control-solid" placeholder="" name="StartDate" value="">
					<!--end::Input-->
					<div class="fv-plugins-message-container invalid-feedback"></div>
				</div>
				<!--end::Input group-->
				<!--begin::Input group-->
				<div class="fv-row mb-15 col-6">
					<!--begin::Label-->
					<label class="fs-6 fw-semibold mb-2">End Date</label>
					<!--end::Label-->
					<!--begin::Input-->
					<input type="date" class="form-control form-control-solid" placeholder="" name="EndDate" value="">
					<!--end::Input-->
				</div>
			</div>
			<!--end::Input group-->
			<!--begin::Billing toggle-->
			<div class="fw-bold fs-3 rotate collapsible mb-7" data-bs-toggle="collapse" href="#kt_modal_add_customer_billing_info" role="button" aria-expanded="false" aria-controls="kt_customer_view_details">
				Contract Information
				<span class="ms-2 rotate-180">
					<!--begin::Svg Icon | path: icons/duotune/arrows/arr072.svg-->
					<span class="svg-icon svg-icon-3">
						<svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
							<path d="M11.4343 12.7344L7.25 8.55005C6.83579 8.13583 6.16421 8.13584 5.75 8.55005C5.33579 8.96426 5.33579 9.63583 5.75 10.05L11.2929 15.5929C11.6834 15.9835 12.3166 15.9835 12.7071 15.5929L18.25 10.05C18.6642 9.63584 18.6642 8.96426 18.25 8.55005C17.8358 8.13584 17.1642 8.13584 16.75 8.55005L12.5657 12.7344C12.2533 13.0468 11.7467 13.0468 11.4343 12.7344Z" fill="currentColor"></path>
						</svg>
					</span>
					<!--end::Svg Icon-->
				</span>
			</div>
			<!--end::Billing toggle-->
			<!--begin::Billing form-->
			<div id="kt_modal_add_customer_billing_info" class="collapse show">
				<!--begin::Input group-->
				<div class="row">
					<div class="d-flex flex-column mb-7 fv-row fv-plugins-icon-container col-6">
						<!--begin::Label-->
						<label class="required fs-6 fw-semibold mb-2">ExcutedBy</label>
						<!--end::Label-->
						<!--begin::Input-->
						<input type="text" class="form-control form-control-solid" placeholder="" name="ExcutedBy" value="">
						<!--end::Input-->
						<div class="fv-plugins-message-container invalid-feedback"></div>
					</div>
					<!--end::Input group-->
					<!--begin::Input group-->
					<div class="d-flex flex-column mb-7 fv-row col-6">
						<!--begin::Label-->
						<label class="fs-6 fw-semibold mb-2">ContractType</label>
						<!--end::Label-->
						<!--begin::Input-->
						<select data-control="select2" name="ContractType" data-placeholder="Select ContractType" id="SelectedColumns" class="form-control">
							<option></option>
							@foreach (var item in Model)
							{

								<option value="@item.TypeId">@item.TypeNameAr</option>
							}
						</select>
						<!--end::Input-->
					</div>
				</div>
				<!--end::Input group-->
				<!--begin::Input group-->
				<div class="row">
					<div class="d-flex flex-column mb-7 fv-row fv-plugins-icon-container col-6">
						<!--begin::Label-->
						<label class="required fs-6 fw-semibold mb-2">ContractValue</label>
						<!--end::Label-->
						<!--begin::Input-->
						<input class="form-control form-control-solid" placeholder="" name="ContractValue" value="">
						<!--end::Input-->
						<div class="fv-plugins-message-container invalid-feedback"></div>
					</div>
					<!--end::Input group-->
					<!--begin::Input group-->
				
						<!--begin::Col-->
						<div class=" fv-row fv-plugins-icon-container col-6">
							<!--begin::Label-->
							<label class="required fs-6 fw-semibold mb-2">IncreasePer</label>
							<!--end::Label-->
							<!--begin::Input-->
							<input type="text" class="form-control form-control-solid" placeholder="" name="IncreasePer" value="">
							<!--end::Input-->
							<div class="fv-plugins-message-container invalid-feedback"></div>
						</div>
						<!--end::Col-->
				
				</div>
				<!--end::Input group-->


			</div>
			<!--end::Billing form-->
		</div>
		<!--end::Scroll-->
	</div>
	<!--end::Modal body-->
	<!--begin::Modal footer-->
	<div class="modal-footer flex-center">
		<!--begin::Button-->
		<button type="reset" id="kt_modal_add_customer_cancel" class="btn btn-light me-3">Discard</button>
		<!--end::Button-->
		<!--begin::Button-->
		<button type="submit" class="btn btn-primary">
			<span class="indicator-label">Submit</span>
			<span class="indicator-progress">
				Please wait...
				<span class="spinner-border spinner-border-sm align-middle ms-2"></span>
			</span>
		</button>
		<!--end::Button-->
	</div>
	<!--end::Modal footer-->
</form>
<script>

	$("#SelectedColumns").select2();
</script>

Views/Contract/Edit.cshtml
@model VendorContract
@{
	ViewData["Title"] = "Edit";
	Layout = null;
}





<form class="form fv-plugins-bootstrap5 fv-plugins-framework" method="post" asp-controller="Contract" asp-action="Edit" id="kt_modal_add_customer_form" data-kt-redirect="../../demo1/dist/apps/customers/list.html">

	<!--begin::hidden info-->
	<input type="hidden" class="form-control form-control-solid" placeholder="" name="VendorId" value="@Model.VendorId">
	<input type="hidden" asp-for="LastUpdateBy">
	<input type="hidden" asp-for="LastUpdateDate" >
	<input type="hidden" asp-for="LastUpdateFrom">
	<!--end::hidden info-->
	
	
		<div class="scroll-y me-n7 pe-7" id="kt_modal_add_customer_scroll" data-kt-scroll="true" data-kt-scroll-activate="{default: false, lg: true}" data-kt-scroll-max-height="auto" data-kt-scroll-dependencies="#kt_modal_add_customer_header" data-kt-scroll-wrappers="#kt_modal_add_customer_scroll" data-kt-scroll-offset="300px" style="max-height: 490px;">
			<!--begin::Input group-->
			<div class="fv-row mb-7 fv-plugins-icon-container">
				<!--begin::Label-->
				<label class="required fs-6 fw-semibold mb-2">Contract Name</label>
				<!--end::Label-->
				<!--begin::Input-->
				<input asp-for="ContractName" class="form-control form-control-solid" placeholder="">
				<!--end::Input-->
				<div class="fv-plugins-message-container invalid-feedback"></div>
			</div>
			<!--end::Input group-->
			<!--begin::Input group-->
			<div class="fv-row mb-7 fv-plugins-icon-container">
				<!--begin::Label-->
				<label class="required fs-6 fw-semibold mb-2">StartDate</label>
				<!--end::Label-->
				<!--begin::Input-->
				<input type="date" class="form-control form-control-solid" placeholder="" name="StartDate" value="@Model.StartDate.ToString("yyyy-MM-dd")">
				<!--end::Input-->
				<div class="fv-plugins-message-container invalid-feedback"></div>
			</div>
			<!--end::Input group-->
			<!--begin::Input group-->
			<div class="fv-row mb-15">
				<!--begin::Label-->
				<label class="fs-6 fw-semibold mb-2">End Date</label>
				<!--end::Label-->
				<!--begin::Input-->
				<input type="date" class="form-control form-control-solid" placeholder="" name="EndDate" value="@(Model.EndDate?.ToString("yyyy-MM-dd"))">


				<!--end::Input-->
			</div>
			<!--end::Input group-->
			<!--begin::Billing toggle-->
			<div class="fw-bold fs-3 rotate collapsible mb-7" data-bs-toggle="collapse" href="#kt_modal_add_customer_billing_info" role="button" aria-expanded="false" aria-controls="kt_customer_view_details">
				Contract Information
				<span class="ms-2 rotate-180">
					<!--begin::Svg Icon | path: icons/duotune/arrows/arr072.svg-->
					<span class="svg-icon svg-icon-3">
						<svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
							<path d="M11.4343 12.7344L7.25 8.55005C6.83579 8.13583 6.16421 8.13584 5.75 8.55005C5.33579 8.96426 5.33579 9.63583 5.75 10.05L11.2929 15.5929C11.6834 15.9835 12.3166 15.9835 12.7071 15.5929L18.25 10.05C18.6642 9.63584 18.6642 8.96426 18.25 8.55005C17.8358 8.13584 17.1642 8.13584 16.75 8.55005L12.5657 12.7344C12.2533 13.0468 11.7467 13.0468 11.4343 12.7344Z" fill="currentColor"></path>
						</svg>
					</span>
					<!--end::Svg Icon-->
				</span>
			</div>
			<!--end::Billing toggle-->
			<!--begin::Billing form-->
			<div id="kt_modal_add_customer_billing_info" class="collapse show">
				<!--begin::Input group-->
				<div class="d-flex flex-column mb-7 fv-row fv-plugins-icon-container">
					<!--begin::Label-->
					<label class="required fs-6 fw-semibold mb-2">ExcutedBy</label>
					<!--end::Label-->
					<!--begin::Input-->
					<input type="text" class="form-control form-control-solid" placeholder="" name="ExcutedBy" value="@Model.ExcutedBy">
					<!--end::Input-->
					<div class="fv-plugins-message-container invalid-feedback"></div>
				</div>
				<!--end::Input group-->
				<!--begin::Input group-->
				<div class="d-flex flex-column mb-7 fv-row">
					<!--begin::Label-->
					<label class="fs-6 fw-semibold mb-2">ContractType</label>
					<!--end::Label-->
					<!--begin::Input-->
					<input type="number" class="form-control form-control-solid" placeholder="" name="ContractType" value="@Model.ContractType">
					<!--end::Input-->
				</div>
				<!--end::Input group-->
				<!--begin::Input group-->
				<div class="d-flex flex-column mb-7 fv-row fv-plugins-icon-container">
					<!--begin::Label-->
					<label class="required fs-6 fw-semibold mb-2">ContractValue</label>
					<!--end::Label-->
					<!--begin::Input-->
					@* <input type="number" class="form-control form-control-solid" placeholder="" name="ContractValue" value="@Model.ContractValue"> *@
					<input type="number" class="form-control form-control-solid" placeholder="" name="ContractValue" value="@Model.ContractValue">
					<!--end::Input-->
					<div class="fv-plugins-message-container invalid-feedback"></div>
				</div>
				<!--end::Input group-->
				<!--begin::Input group-->
				<div class="row g-9 mb-7">
					<!--begin::Col-->
					<div class="col-md-6 fv-row fv-plugins-icon-container">
						<!--begin::Label-->
						<label class="required fs-6 fw-semibold mb-2">IncreasePer</label>
						<!--end::Label-->
						<!--begin::Input-->
						<input type="text" class="form-control form-control-solid" placeholder="" name="IncreasePer" value="@Model.IncreasePer">
						<!--end::Input-->
						<div class="fv-plugins-message-container invalid-feedback"></div>
					</div>
					<!--end::Col-->
				</div>
				<!--end::Input group-->
			</div>
			<!--end::Billing form-->
		</div>
		<!--end::Scroll-->
	
	<!--end::Modal body-->
	<!--begin::Modal footer-->
	<div class="modal-footer flex-center">
		<!--begin::Button-->
		<button type="reset" id="kt_modal_add_customer_cancel" class="btn btn-light me-3">Discard</button>
		<!--end::Button-->
		<!--begin::Button-->
		<button type="submit" id="kt_modal_add_customer_submit" class="btn btn-primary">
			<span class="indicator-label">Submit</span>
			<span class="indicator-progress">
				Please wait...
				<span class="spinner-border spinner-border-sm align-middle ms-2"></span>
			</span>
		</button>
		<!--end::Button-->
	</div>
	<!--end::Modal footer-->
</form>

Views/Contract/_EditContractPartialView.cshtml
@model VendorContract 



<form class="form fv-plugins-bootstrap5 fv-plugins-framework" method="post" asp-controller="Contract" asp-action="Edit" id="kt_modal_add_customer_form" data-kt-redirect="../../demo1/dist/apps/customers/list.html">

	<!--begin::hidden info-->
	<input type="hidden" class="form-control form-control-solid" placeholder="" name="VendorId" value="@Model.VendorId">
	<!--end::hidden info-->
	<!--begin::Modal header-->
	<div class="modal-header" id="kt_modal_add_customer_header">
		<!--begin::Modal title-->
		<h2 class="fw-bold">Edit a Contract</h2>
		<!--end::Modal title-->
		<!--begin::Close-->
		<div id="kt_modal_add_customer_close" class="btn btn-icon btn-sm btn-active-icon-primary">
			<!--begin::Svg Icon | path: icons/duotune/arrows/arr061.svg-->
			<span class="svg-icon svg-icon-1">
				<svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
					<rect opacity="0.5" x="6" y="17.3137" width="16" height="2" rx="1" transform="rotate(-45 6 17.3137)" fill="currentColor"></rect>
					<rect x="7.41422" y="6" width="16" height="2" rx="1" transform="rotate(45 7.41422 6)" fill="currentColor"></rect>
				</svg>
			</span>
			<!--end::Svg Icon-->
		</div>
		<!--end::Close-->
	</div>
	<!--end::Modal header-->
	<!--begin::Modal body-->
	<div class="modal-body py-10 px-lg-17">
		<!--begin::Scroll-->
		<div class="scroll-y me-n7 pe-7" id="kt_modal_add_customer_scroll" data-kt-scroll="true" data-kt-scroll-activate="{default: false, lg: true}" data-kt-scroll-max-height="auto" data-kt-scroll-dependencies="#kt_modal_add_customer_header" data-kt-scroll-wrappers="#kt_modal_add_customer_scroll" data-kt-scroll-offset="300px" style="max-height: 490px;">
			<!--begin::Input group-->
			<div class="fv-row mb-7 fv-plugins-icon-container">
				<!--begin::Label-->
				<label class="required fs-6 fw-semibold mb-2">Contract Name</label>
				<!--end::Label-->
				<!--begin::Input-->
				<input  asp-for="ContractName" class="form-control form-control-solid" placeholder="" >
				<!--end::Input-->
				<div class="fv-plugins-message-container invalid-feedback"></div>
			</div>
			<!--end::Input group-->
			<!--begin::Input group-->
			<div class="fv-row mb-7 fv-plugins-icon-container">
				<!--begin::Label-->
				<label class="required fs-6 fw-semibold mb-2">StartDate</label>
				<!--end::Label-->
				<!--begin::Input-->
				<input type="date" class="form-control form-control-solid" placeholder="" name="StartDate" value="@Model.StartDate.ToString("yyyy-MM-dd")">
				<!--end::Input-->
				<div class="fv-plugins-message-container invalid-feedback"></div>
			</div>
			<!--end::Input group-->
			<!--begin::Input group-->
			<div class="fv-row mb-15">
				<!--begin::Label-->
				<label class="fs-6 fw-semibold mb-2">End Date</label>
				<!--end::Label-->
				<!--begin::Input-->
				<input type="date" class="form-control form-control-solid" placeholder="" name="EndDate" value="@(Model.EndDate?.ToString("yyyy-MM-dd"))">


				<!--end::Input-->
			</div>
			<!--end::Input group-->
			<!--begin::Billing toggle-->
			<div class="fw-bold fs-3 rotate collapsible mb-7" data-bs-toggle="collapse" href="#kt_modal_add_customer_billing_info" role="button" aria-expanded="false" aria-controls="kt_customer_view_details">
				Contract Information
				<span class="ms-2 rotate-180">
					<!--begin::Svg Icon | path: icons/duotune/arrows/arr072.svg-->
					<span class="svg-icon svg-icon-3">
						<svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
							<path d="M11.4343 12.7344L7.25 8.55005C6.83579 8.13583 6.16421 8.13584 5.75 8.55005C5.33579 8.96426 5.33579 9.63583 5.75 10.05L11.2929 15.5929C11.6834 15.9835 12.3166 15.9835 12.7071 15.5929L18.25 10.05C18.6642 9.63584 18.6642 8.96426 18.25 8.55005C17.8358 8.13584 17.1642 8.13584 16.75 8.55005L12.5657 12.7344C12.2533 13.0468 11.7467 13.0468 11.4343 12.7344Z" fill="currentColor"></path>
						</svg>
					</span>
					<!--end::Svg Icon-->
				</span>
			</div>
			<!--end::Billing toggle-->
			<!--begin::Billing form-->
			<div id="kt_modal_add_customer_billing_info" class="collapse show">
				<!--begin::Input group-->
				<div class="d-flex flex-column mb-7 fv-row fv-plugins-icon-container">
					<!--begin::Label-->
					<label class="required fs-6 fw-semibold mb-2">ExcutedBy</label>
					<!--end::Label-->
					<!--begin::Input-->
					<input type="text" class="form-control form-control-solid" placeholder="" name="ExcutedBy" value="@Model.ExcutedBy">
					<!--end::Input-->
					<div class="fv-plugins-message-container invalid-feedback"></div>
				</div>
				<!--end::Input group-->
				<!--begin::Input group-->
				<div class="d-flex flex-column mb-7 fv-row">
					<!--begin::Label-->
					<label class="fs-6 fw-semibold mb-2">ContractType</label>
					<!--end::Label-->
					<!--begin::Input-->
					<input type="number" class="form-control form-control-solid" placeholder="" name="ContractType" value="@Model.ContractType">
					<!--end::Input-->
				</div>
				<!--end::Input group-->
				<!--begin::Input group-->
				<div class="d-flex flex-column mb-7 fv-row fv-plugins-icon-container">
					<!--begin::Label-->
					<label class="required fs-6 fw-semibold mb-2">ContractValue</label>
					<!--end::Label-->
					<!--begin::Input-->
					@* <input type="number" class="form-control form-control-solid" placeholder="" name="ContractValue" value="@Model.ContractValue"> *@
					<input type="number" class="form-control form-control-solid" placeholder="" name="ContractValue" value="@Model.ContractValue">
					<!--end::Input-->
					<div class="fv-plugins-message-container invalid-feedback"></div>
				</div>
				<!--end::Input group-->
				<!--begin::Input group-->
				<div class="row g-9 mb-7">
					<!--begin::Col-->
					<div class="col-md-6 fv-row fv-plugins-icon-container">
						<!--begin::Label-->
						<label class="required fs-6 fw-semibold mb-2">IncreasePer</label>
						<!--end::Label-->
						<!--begin::Input-->
						<input type="text" class="form-control form-control-solid" placeholder="" name="IncreasePer" value="@Model.IncreasePer">
						<!--end::Input-->
						<div class="fv-plugins-message-container invalid-feedback"></div>
					</div>
					<!--end::Col-->
				</div>
				<!--end::Input group-->
			</div>
			<!--end::Billing form-->
		</div>
		<!--end::Scroll-->
	</div>
	<!--end::Modal body-->
	<!--begin::Modal footer-->
	<div class="modal-footer flex-center">
		<!--begin::Button-->
		<button type="reset" id="kt_modal_add_customer_cancel" class="btn btn-light me-3">Discard</button>
		<!--end::Button-->
		<!--begin::Button-->
		<button type="submit" id="kt_modal_add_customer_submit" class="btn btn-primary">
			<span class="indicator-label">Submit</span>
			<span class="indicator-progress">
				Please wait...
				<span class="spinner-border spinner-border-sm align-middle ms-2"></span>
			</span>
		</button>
		<!--end::Button-->
	</div>
	<!--end::Modal footer-->
</form>