Models/PatientInvoice.cs
using System;
using System.Collections.Generic;

namespace LAB.Models;

public partial class PatientInvoice
{
    public int InvoiceId { get; set; }

    public DateTime CreationDate { get; set; }

    public string? InvoiceNotes { get; set; }

    public double InvoiceCost { get; set; }

    public string Currency { get; set; } = null!;

    public string PaymentType { get; set; } = null!;

    public int VisitId { get; set; }

    public string InvoiceStatus { get; set; } = null!;

    public string LastUpdateBy { get; set; } = null!;

    public string LastUpdateFrom { get; set; } = null!;

    public DateTime LastUpdateDate { get; set; }

    public double? PaidValue { get; set; }

    public bool IsSupply { get; set; }

    public virtual ICollection<InvoicesPaying> InvoicesPayings { get; set; } = new List<InvoicesPaying>();

    public virtual ICollection<PatientInvoiceDetail> PatientInvoiceDetails { get; set; } = new List<PatientInvoiceDetail>();

    public virtual Visit Visit { get; set; } = null!;
}

Controllers/PatientInvoiceController.cs
using LAB.IService;
using LAB.Models;
using LAB.ViewModel;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace LAB.Controllers
{
	public class PatientInvoiceController : Controller
	{
		private readonly IUnitOfWork _unitofwork;

		public PatientInvoiceController(IUnitOfWork unitOfWork) 
		{
			_unitofwork=unitOfWork;
		}

		public IActionResult Index()
		{

			var date =DateOnly.FromDateTime(DateTime.Now);
			var modal = _unitofwork.PatientInvoiceServices.GetAll();
			//var modal = _unitofwork.PatientInvoiceServices.GetAll().Where(d=>DateOnly.FromDateTime( d.CreationDate) == date );
			foreach (var item in modal)
			{
				if (item.InvoiceStatus.ToLower() == "p")
				{ item.InvoiceStatus = "pending"; }
				else if (item.InvoiceStatus.ToLower() == "a")
				{ item.InvoiceStatus = "Active"; }
				else if (item.InvoiceStatus.ToLower() == "c")
				{ item.InvoiceStatus = "Cancel";
				    
				
				}

			}

			return View(modal);
		}


		public IActionResult GetInvoice() 
		{
			var model = _unitofwork.PatientInvoiceServices.GetAll();

			foreach (var item in model)
			{
				if (item.InvoiceStatus.ToLower() == "p")
				{ item.InvoiceStatus = "pending"; }
				else if (item.InvoiceStatus.ToLower() == "a")
				{ item.InvoiceStatus = "Active"; }
				else if (item.InvoiceStatus.ToLower() == "c")
				{ item.InvoiceStatus = "Cancel"; }

			}

			return View("Index", model);
		}

		[HttpGet]
		public IActionResult PatientInvoicePay(int id )
		{

			var modal = _unitofwork.PatientInvoiceServices.GetByVisitId(id);
			
			modal.LastUpdateDate= DateTime.Now;
			modal.LastUpdateFrom = "hr";
			modal.LastUpdateBy = "hr";
			int vendorId;


             ViewData["servicelist"] = _unitofwork.VisitServiceServices.GetServicesByVisitId(id);
			if (modal.Visit.VisitInsurred)
			{
				 vendorId = (int)modal.Visit.VisitInsurredCompanyId;
				ViewData["VendorName"] = _unitofwork.VendorService.GetById(vendorId).VendorName;

			}
			else
			{
				ViewData["VendorName"] = "LaB";
			}
			

                  //no max
			if (modal.Visit.VisitInsurred == true)
			{

				
				var visitcopayment = modal.Visit.Copayment;

				

				if (modal.Visit.ApprovalMaxLimit == 0)
				{
					var patientcost_Max0 =modal.InvoiceCost * (visitcopayment / 100);

					ViewData["PatientCost"] = patientcost_Max0;
					ViewData["VendorCost"] = modal.InvoiceCost - patientcost_Max0;



				}
				else
				{
					//if (modal.Visit.PatientApprovalNum !=null || modal.Visit.PatientApprovalNum =="")
					//{
                        if(modal.Visit.ApprovalMaxLimit > modal.InvoiceCost)
					     {


						  var	PatientCost_maxLimit =modal.InvoiceCost * (visitcopayment / 100);
							ViewData["PatientCost"] = PatientCost_maxLimit;
							ViewData["VendorCost"] = modal.InvoiceCost - PatientCost_maxLimit;

						}
					     else
					      {
							if (modal.Visit.PatientApprovalNum != null || modal.Visit.PatientApprovalNum == "")
							{
								var PatientCost_maxLimit = modal.InvoiceCost * (visitcopayment / 100);
								ViewData["PatientCost"] = PatientCost_maxLimit;
								ViewData["VendorCost"] = modal.InvoiceCost - PatientCost_maxLimit;
							}
							else
							{
								var ValueLeft = modal.InvoiceCost - modal.Visit.ApprovalMaxLimit;

								var CopaymentValue = modal.Visit.ApprovalMaxLimit * (visitcopayment / 100);

								var PatientCost_MinLimit = CopaymentValue + ValueLeft;

								ViewData["PatientCost"] = PatientCost_MinLimit;


								ViewData["VendorCost"] = modal.InvoiceCost - PatientCost_MinLimit;
							}
							


						}
					//}
					//else
					//{
					//	var PatientCostNotAprronum = modal.InvoiceCost * (visitcopayment / 100);

					//	ViewData["PatientCost"] =  PatientCostNotAprronum;
					//	ViewData["VendorCost"] = modal.InvoiceCost - PatientCostNotAprronum;
					//}
					
				}



				return View(modal);
			}

			else
			{
				if(modal.Visit.DiscountCard != null && modal.Visit.DiscountCard != 0)
				{
					

					var discount = modal.Visit.DiscountCard;

					var PatientCostDiscount = modal.InvoiceCost * (discount / 100);

					ViewData["PatientCost"] = PatientCostDiscount;
					

				}

				else
				{
					ViewData["PatientCost"] = modal.InvoiceCost - (modal.PaidValue??0);

				}
			}

			return View("DiscountView",modal);
		}
		[HttpPost]
		public IActionResult Pay( double paidValue , int InvoiceId , double PatientCost, double InvoiceCost)
		{
			InvoicesPaying p = new InvoicesPaying()
			{
				InvoiceId = InvoiceId,
				PayingValue= paidValue,
				LastUpdateFrom=":::1",
				LastUpdateBy="abdo",
				PayingDate= DateTime.Now,
			};
			var invoice = _unitofwork._Context.PatientInvoices.Include(x => x.Visit).FirstOrDefault(x => x.InvoiceId == InvoiceId);
			

			if (invoice.PaidValue != null) 
			invoice.PaidValue += paidValue;
			else
			invoice.PaidValue = paidValue;

			var visit = _unitofwork._Context.Visits.FirstOrDefault(x => x.VisitId == invoice.VisitId);

			visit.VisitStatus = "A";
			invoice.InvoiceStatus = "A";

			_unitofwork._Context.Update(visit);
			_unitofwork._Context.Update(invoice);
			_unitofwork._Context.InvoicesPayings.Add(p);
			_unitofwork.Save();
			double? totalPaiedValue = invoice.PaidValue;

			var result = new { status = "ok", remainingvalue = PatientCost - totalPaiedValue, paidValue = paidValue };
			return Json(result);
		}


		[HttpPost]
		public IActionResult Filter(DateOnly Date)
		{
			//, DateOnly EndDate

			//var model = _unitofwork.PatientInvoiceServices.GetAll().Where(i => DateOnly.FromDateTime(i.CreationDate) >= StartDate && DateOnly.FromDateTime(i.CreationDate) <= EndDate).ToList();
			
			var model = _unitofwork.PatientInvoiceServices.GetAll().Where(i => DateOnly.FromDateTime(i.CreationDate) >= Date).ToList();


			foreach (var item in model)
			{
				if (item.InvoiceStatus.ToLower() == "p")
				{ item.InvoiceStatus = "pending"; }
				else if (item.InvoiceStatus.ToLower() == "a")
				{ item.InvoiceStatus = "Active"; }
				else if (item.InvoiceStatus.ToLower() == "c")
				{ item.InvoiceStatus = "Cancel"; }

			}


			return View(model);
		}


		[HttpGet]
		public IActionResult Cancle(int id)
		{

			var modal = _unitofwork.PatientInvoiceServices.GetByVisitId(id);

			modal.LastUpdateDate = DateTime.Now;
			modal.LastUpdateFrom = "hr";
			modal.LastUpdateBy = "hr";
			int vendorId;

			if (modal.Visit.VisitInsurred)
			{
				vendorId = (int)modal.Visit.VisitInsurredCompanyId;
				ViewData["VendorName"] = _unitofwork.VendorService.GetById(vendorId).VendorName;

			}
			else
			{
				ViewData["VendorName"] = "LaB";
			}
            ViewData["servicelist"] = _unitofwork.VisitServiceServices.GetServicesByVisitId(id);

            return View(modal);
		}

		//filter by date
	   [HttpPost]
		public IActionResult FilterByDate(DateOnly Date)
		{

			var model = _unitofwork.PatientInvoiceServices.GetAll().Where(i => DateOnly.FromDateTime(i.CreationDate) == Date).ToList();


			return View("Filter", model);
		}

	}
}

Views/PatientInvoice/Filter.cshtml
@model IEnumerable<LAB.Models.PatientInvoice>


<link href="~/plugins/custom/datatables/datatables.bundle.css" rel="stylesheet" />
<link href="~/plugins/global/plugins.bundle.css" rel="stylesheet" type="text/css" />
<div id="kt_app_content" class="app-content flex-column-fluid">
	<!--begin::Content container-->
	<div id="kt_app_content_container" class="app-container container-xxl">
		<!--begin::Card-->
		<div class="card">
			<!--begin::Card header-->
			<div class="card-header border-0 pt-6">
				<!--begin::Card title-->
				<div class="card-title">

					<!--begin::Search-->



					<div class="row">
						<div class="d-flex align-items-center position-relative my-1">
							<!--begin::Svg Icon | path: icons/duotune/general/gen021.svg-->
							<span class="svg-icon svg-icon-1 position-absolute ms-6">
								<svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
									<rect opacity="0.5" x="17.0365" y="15.1223" width="8.15546" height="2" rx="1" transform="rotate(45 17.0365 15.1223)" fill="currentColor"></rect>
									<path d="M11 19C6.55556 19 3 15.4444 3 11C3 6.55556 6.55556 3 11 3C15.4444 3 19 6.55556 19 11C19 15.4444 15.4444 19 11 19ZM11 5C7.53333 5 5 7.53333 5 11C5 14.4667 7.53333 17 11 17C14.4667 17 17 14.4667 17 11C17 7.53333 14.4667 5 11 5Z" fill="currentColor"></path>
								</svg>
							</span>
							<!--end::Svg Icon-->
							<input type="text" data-kt-customer-table-filter="search" class="form-control form-control-solid w-250px ps-15" placeholder="Search invoice" id="listsearch" />
						</div>
					</div>



					<!--end::Search-->

				</div>
				<!--begin::Card title-->
				<!--begin::Card toolbar-->
				<div class="card-toolbar">
					<!--begin::Toolbar-->
					<div class="d-flex justify-content-end" data-kt-customer-table-toolbar="base">
				

						<!---test date                                               //////////////////////////////////////////////////// filter->


						<div> <input class="form-control form-control-solid" placeholder="Pick date rage" id="kt_daterangepicker_4"/></div>



						<!---end                                    test               /////////////////////////////////////////////         date filter->
						<!--end::filter----------------------------------------------------------------->
						<!--begin::Export-->

						<button type="button" class="btn btn-light-primary me-3" onclick="exportToExcel()">
							<!--begin::Svg Icon | path: icons/duotune/arrows/arr078.svg-->
							<span class="svg-icon svg-icon-2">
								<svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
									<rect opacity="0.3" x="12.75" y="4.25" width="12" height="2" rx="1" transform="rotate(90 12.75 4.25)" fill="currentColor" />
									<path d="M12.0573 6.11875L13.5203 7.87435C13.9121 8.34457 14.6232 8.37683 15.056 7.94401C15.4457 7.5543 15.4641 6.92836 15.0979 6.51643L12.4974 3.59084C12.0996 3.14332 11.4004 3.14332 11.0026 3.59084L8.40206 6.51643C8.0359 6.92836 8.0543 7.5543 8.44401 7.94401C8.87683 8.37683 9.58785 8.34458 9.9797 7.87435L11.4427 6.11875C11.6026 5.92684 11.8974 5.92684 12.0573 6.11875Z" fill="currentColor" />
									<path opacity="0.3" d="M18.75 8.25H17.75C17.1977 8.25 16.75 8.69772 16.75 9.25C16.75 9.80228 17.1977 10.25 17.75 10.25C18.3023 10.25 18.75 10.6977 18.75 11.25V18.25C18.75 18.8023 18.3023 19.25 17.75 19.25H5.75C5.19772 19.25 4.75 18.8023 4.75 18.25V11.25C4.75 10.6977 5.19771 10.25 5.75 10.25C6.30229 10.25 6.75 9.80228 6.75 9.25C6.75 8.69772 6.30229 8.25 5.75 8.25H4.75C3.64543 8.25 2.75 9.14543 2.75 10.25V19.25C2.75 20.3546 3.64543 21.25 4.75 21.25H18.75C19.8546 21.25 20.75 20.3546 20.75 19.25V10.25C20.75 9.14543 19.8546 8.25 18.75 8.25Z" fill="currentColor" />
								</svg>
							</span>
							<!--end::Svg Icon-->Export
						</button>
						<!--end::Export-->

					</div>
					<!--end::Card toolbar-->
				</div>
				<!--end::Card header-->
				<!--begin::Card body-->
				<div class="card-body pt-0">
					<!--begin::Table-->
			
					<table class="table align-middle table-row-dashed fs-6 gy-5 dataTable no-footer" id="listtable">
						<!--begin::Table head-->
						<thead>
							<!--begin::Table row-->
							<tr class="text-start text-gray-400 fw-bold fs-7 text-uppercase gs-0">

								<th class="min-w-125px sorting text-dark " tabindex="0" aria-controls="kt_customers_table" rowspan="1" colspan="1" aria-label="Customer Name: activate to sort column ascending" style="width: 172.391px;">Patient Name</th>
								<th class="min-w-125px sorting text-dark " tabindex="0" aria-controls="kt_customers_table" rowspan="1" colspan="1" aria-label="Email: activate to sort column ascending" style="width: 213.356px;">Invoice ID</th>
							
								<th class="min-w-125px sorting text-dark " tabindex="0" aria-controls="kt_customers_table" rowspan="1" colspan="1" aria-label="Company: activate to sort column ascending" style="width: 189.524px;">Invoice Status</th>
								<th class="min-w-125px sorting text-dark " tabindex="0" aria-controls="kt_customers_table" rowspan="1" colspan="1" aria-label="Payment Method: activate to sort column ascending" style="width: 172.391px;">Creation Date</th>
								<th class="min-w-125px sorting text-dark " tabindex="0" aria-controls="kt_customers_table" rowspan="1" colspan="1" aria-label="Created Date: activate to sort column ascending" style="width: 223.967px;">Payment Type</th>
							
								<th class="min-w-125px sorting text-dark " tabindex="0" aria-controls="kt_customers_table" rowspan="1" colspan="1" aria-label="Created Date: activate to sort column ascending" style="width: 223.967px;">Status</th>
							
							</tr>
							<!--end::Table row-->
						</thead>
						<!--end::Table head-->
						<!--begin::Table body-->
						<tbody class="fw-semibold text-gray-600">

							@foreach (PatientInvoice item in Model)
							{

								<tr class="odd">


									<!--begin::Name=-->
									<td>

										<div class="position-relative ps-6 pe-3 py-2">
											<div class="position-absolute start-0 top-0 w-4px h-100 rounded-2 " id="myDiv"></div>
											<div> @item.Visit.Patient.PatientName</div>
										</div>
									</td>
									<!--end::Name=-->
								
									<!--begin::Patient Email=-->
									<td id="InvoiceStatus">
										@item.InvoiceStatus
									</td>
									<!--end::Patient Email=-->
									<!--begin::Patient Gender=-->
									<td>
										@DateOnly.FromDateTime(item.CreationDate)
									</td>
									<!--end::Patient Gender=-->
									<!--begin::Patient Gender=-->
									<td>
										@item.PaymentType
									</td>
									<td>

										<a class="text-info fw-bold mb-3 badge badge-light-secondary" href="/PatientInvoice/PatientInvoicePay/@item.Visit.VisitId"><i class="fa-solid fa-sack-dollar fa-lg" style="color: #40969c;"></i></a>


										<a asp-action="Details" asp-controller="Visit" asp-route-id="@item.Visit.VisitId" class=" badge badge-light-primary text-info fw-bold"><i class="fa-solid fa-paste fa-lg" style="color: #e57e2a;"></i></a>



										<a asp-action="Cancle" asp-controller="PatientInvoice" asp-route-id="@item.Visit.VisitId" class=" badge badge-light-danger text-info fw-bold"><i class="fa-solid fa-rectangle-xmark fa-lg" style="color: #b2385d;"></i></a>



									</td>
									<!--end::Patient Gender=-->
								</tr>

							}


						</tbody>
						<!--end::Table body-->
					</table>
				

				</div>
			</div>
		</div>
		<!--end::Modal - Customers - Add-->
		<!--begin::Modal - Adjust Balance-->
		<div class="modal fade" id="kt_customers_export_modal" tabindex="-1" aria-hidden="true">
			<!--begin::Modal dialog-->
			<div class="modal-dialog modal-dialog-centered mw-650px">
			</div>
			<!--end::Modal dialog-->
		</div>
		<!--end::Modal - New Card-->
		<!--end::Modals-->
	</div>
	<!--end::Content container-->


	<script src="https://unpkg.com/exceljs/dist/exceljs.min.js"></script>
	<script src="https://unpkg.com/xlsx/dist/xlsx.full.min.js"></script>
	<script src="~/plugins/custom/datatables/datatables.bundle.js"></script>


	<script>


		var rows = document.querySelectorAll("#listtable tbody tr");

		rows.forEach(function (row) {
			var invoiceStatusCell = row.querySelector("#InvoiceStatus");
			var invoiceStatus = invoiceStatusCell.textContent.trim();
			var div = row.querySelector("#myDiv");

			if (invoiceStatus === 'Active' || invoiceStatus === 'A') {
				div.style.backgroundColor = 'green';
			}
			else if (invoiceStatus === 'pending' || invoiceStatus === 'p') {
				div.style.backgroundColor = 'yellow';
			}

			else if (invoiceStatus === 'Cancel' || invoiceStatus === 'c') {
				div.style.backgroundColor = 'red';
			}

		});


	</script>


	@* message error validation *@
	<script>
		function validateForm() {
			var startDateInput = document.getElementById('startDate');
			var EndDateInput = document.getElementById('EndDate');
			var startDate = new Date(startDateInput.value);
			var EndDate = new Date(EndDateInput.value);
			var currentDate = new Date();

			if (startDate > currentDate) {
				alert("Invalid date. Start Date cannot be in the future.");
				return false; // Prevent form submission
			}
			else if (EndDate < startDate) {
				alert("Invalid date. End Date less than Start date");
				return false; // Prevent form submission
			}
			return true; // Form submission is allowed
		}
	</script>








	@section Scripts
		{
		<script src="https://unpkg.com/exceljs/dist/exceljs.min.js"></script>
		<script src="https://unpkg.com/xlsx/dist/xlsx.full.min.js"></script>
		<script src="~/plugins/custom/datatables/datatables.bundle.js"></script>

		<script>
			$('#listsearch').on('keyup', function () {
				table.search(this.value).draw();
			});

			var table = $("#listtable").DataTable({
				"aaSorting": [],
			});


			// Function to export data to Excel
			function exportToExcel() {
				// Get the data from the table
				var data = table.rows().data().toArray();

				// Create a new workbook
				var workbook = new ExcelJS.Workbook();
				var worksheet = workbook.addWorksheet('Sheet1');

				// Add header row
				var header = [];
				$("#listtable thead th").each(function () {
					header.push($(this).text());
				});
				worksheet.addRow(header);

				// Add data rows
				data.forEach(function (row) {
					worksheet.addRow(row);
				});

				// Create a blob for the workbook
				workbook.xlsx.writeBuffer().then(function (buffer) {
					// Create a Blob object and create a URL to trigger the download
					var blob = new Blob([buffer], { type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet' });
					var url = window.URL.createObjectURL(blob);

					// Create a link and trigger the download
					var a = document.createElement('a');
					a.href = url;
					a.download = 'ExportedData.xlsx';
					a.click();

					// Clean up
					window.URL.revokeObjectURL(url);
				});

			}




		</script>





	}

	<script src="~/plugins/global/plugins.bundle.js"></script>

	<script>
		var start = moment().subtract(29, "days");
		var end = moment();

		function cb(start, end) {
			$("#kt_daterangepicker_4").html(start.format("MMMM D, YYYY") + " - " + end.format("MMMM D, YYYY"));
		}

		$("#kt_daterangepicker_4").daterangepicker({
			startDate: start,
			endDate: end,
			ranges: {
				"Today": [moment(), moment()],
				"Yesterday": [moment().subtract(1, "days"), moment().subtract(1, "days")],
				"Last 7 Days": [moment().subtract(6, "days"), moment()],
				"Last 30 Days": [moment().subtract(29, "days"), moment()],
				"This Month": [moment().startOf("month"), moment().endOf("month")],
				"Last Month": [moment().subtract(1, "month").startOf("month"), moment().subtract(1, "month").endOf("month")]
			}
		}, cb);

		cb(start, end);
	</script>