Models/Visit.cs
using System;
using System.Collections.Generic;

namespace LAB.Models;

public partial class Visit
{
    public int VisitId { get; set; }

    public int? PatientId { get; set; }

    public DateTime? VisitStartDate { get; set; }

    public DateTime? VisitEndDate { get; set; }

    public string? VisitNote { get; set; }

    public bool VisitInsurred { get; set; }

    public int? VisitInsurredCompanyId { get; set; }

    public int? RelativeId { get; set; }

    public string VisitStatus { get; set; } = null!;

    public int BranchId { get; set; }

    public string LastUpdateBy { get; set; } = null!;

    public string LastUpdateFrom { get; set; } = null!;

    public DateTime LastUpdateDate { get; set; }

    public string? InvestigationNotes { get; set; }

    public string VisitType { get; set; } = null!;

    public double? Copayment { get; set; }

    public string? PatientInssurredId { get; set; }

    public string? PatientApprovalNum { get; set; }

    public double? ApprovalMaxLimit { get; set; }

    public DateTime? InssuredExpireDate { get; set; }

    public double? DiscountCard { get; set; }

    public int? RelatedVisit { get; set; }

    public int? RefererDoctor { get; set; }

    public int? VisitSource { get; set; }

    public int? OrderId { get; set; }

    public virtual Patient? Patient { get; set; }

    public virtual ICollection<PatientInvoiceDetail> PatientInvoiceDetails { get; set; } = new List<PatientInvoiceDetail>();

    public virtual ICollection<PatientInvoice> PatientInvoices { get; set; } = new List<PatientInvoice>();

    public virtual RefferedDoctor? RefererDoctorNavigation { get; set; }

    public virtual ICollection<ServiceBarcode> ServiceBarcodes { get; set; } = new List<ServiceBarcode>();

    public virtual ICollection<VisitService> VisitServices { get; set; } = new List<VisitService>();
}

Controllers/VisitController.cs
//using IronBarCode;
//using iTextSharp.text.pdf;
//using LAB.IService;
//using LAB.Models;
//using LAB.ViewModel;
//using Microsoft.AspNetCore.Mvc;
//using Microsoft.EntityFrameworkCore;
//using System.Reflection.Metadata;
//using ZXing.OneD;
//using iTextSharp.text;
//using iTextSharp.text.pdf;
//using Org.BouncyCastle.Asn1.Pkcs;
//using LAB.Service;
//using iText.Layout.Element;
using IronBarCode;
using LAB.IService;
using LAB.Models;
using LAB.Service;
using LAB.ViewModel;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using static System.Runtime.InteropServices.JavaScript.JSType;

namespace LAB.Controllers
{
    public class VisitController : Controller
    {

        IUnitOfWork unitOfWork;
        private readonly IWebHostEnvironment hostingEnvironment;

        public VisitController(IUnitOfWork unitOfWork, IWebHostEnvironment hostingEnvironment)
        {
            this.unitOfWork = unitOfWork;
            this.hostingEnvironment = hostingEnvironment;
        }

        public IActionResult Index()
        {

			var date = DateTime.Now;
			//var model = unitOfWork.VisitServices.GetAll().Where(d => DateOnly.FromDateTime(d.VisitStartDate.Value) == DateOnly.FromDateTime(date)); 
			var model = unitOfWork.VisitServices.GetAll();
			foreach (var item in model)
			{
				if (item.VisitStatus.ToLower() == "p")
				{ item.VisitStatus = "pending"; }
				else if (item.VisitStatus.ToLower() == "a")
				{ item.VisitStatus = "Active"; }
				else if (item.VisitStatus.ToLower() == "c")
				{ item.VisitStatus = "Cancel"; }

             
			}

			return View(model);
        }


		[HttpPost]
		public IActionResult Filter(DateOnly? Date)
		{
			//, DateOnly EndDate

			//var model = _unitofwork.PatientInvoiceServices.GetAll().Where(i => DateOnly.FromDateTime(i.CreationDate) >= StartDate && DateOnly.FromDateTime(i.CreationDate) <= EndDate).ToList();


			
			var model = unitOfWork.VisitServices.GetAll().Where(d => DateOnly.FromDateTime( d.VisitStartDate.Value) == Date) .ToList();


			foreach (var item in model)
			{
				if (item.VisitStatus.ToLower() == "p")
				{ item.VisitStatus = "pending"; }
				else if (item.VisitStatus.ToLower() == "a")
				{ item.VisitStatus = "Active"; }
				else if (item.VisitStatus.ToLower() == "c")
				{ item.VisitStatus = "Cancel"; }


			}


			return View("Index", model);
		}

		[HttpGet]
        public IActionResult Add()
        {
            VisitViewModel model = new VisitViewModel();

            model.Visit = new Visit()
            {
                VisitType = "LB",
                LastUpdateBy = "abdo",
                LastUpdateDate = DateTime.Now,
                LastUpdateFrom = "::1",
                VisitStartDate = DateTime.Now,
                VisitStatus = "P"
            };
            model.RefDoctor = unitOfWork._Context.RefferedDoctors.ToList();
            model.Patients = unitOfWork.PatientService.GetAll().ToList();
            model.ServicesPricelists = unitOfWork.servicesPricelistService.GetAll().Where(x=>x.ContractId == 8 ).ToList();
            model.Vendors = unitOfWork.VendorService.GetAll().Where(x => x.VendorCat == 6).ToList();
            model.L2LVendor = unitOfWork.VendorService.GetLab2LabVendor();




			return View(model);
        }

        [HttpPost]
        public IActionResult Add(VisitViewModel model, string? DoctorName, Patient patient, List<int> selecSelectedServices, List<int> SelectedServicesLab2Lab, List<int> SelectedServicesDiscount)
        {
            //update RefferedDoctor if exisit & add if not
            if (DoctorName != null)
            {

                var doctor = unitOfWork._Context.RefferedDoctors.FirstOrDefault(x => x.DoctorName.ToLower() == DoctorName.ToLower()) ?? new RefferedDoctor() {DoctorName= DoctorName, LastUpdateBy = "abdo", LastUpdateDate = DateTime.Now, LastUpdateFrom = ":::1" };

                unitOfWork._Context.Update(doctor);
                unitOfWork.Save();
                model.Visit.RefererDoctor = doctor.DrId;
            }

            for (int i = 0; i < selecSelectedServices.Count; i++)
            {
                model.VisitserviceViewModel.Add(new VisitserviceViewModel() { SelectedServices = selecSelectedServices[i], SelectedServicesDiscount = SelectedServicesDiscount[i], SelectedServicesLab2Lab = SelectedServicesLab2Lab[i] });
            }
            double totalcost = 0;

            if (ModelState.IsValid)
            {
                if (patient.PatientId == 0)
                {
                    patient.CreationDate = DateTime.Now;
                }
                else
                {
                    patient.LastUpdateDate = DateTime.Now;
                }

                unitOfWork.PatientService.Update(patient);
                unitOfWork.Save();
                model.Visit.PatientId = patient.PatientId;
                model.Visit.VisitStatus = "P";
                unitOfWork.VisitServices.Add(model.Visit);
                unitOfWork.Save();
                //var vid = model.Visit.VisitId;

                if (model.VisitserviceViewModel.Count > 0)
                {
                    foreach (var item in model.VisitserviceViewModel)
                    {
                        var numerForServiceInVisit = unitOfWork.VisitServiceServices.GetByServiceIdAndVisitId(item.SelectedServices, model.Visit.VisitId).Count;

                        if (item.SelectedServicesLab2Lab == 0)
                        {
                            item.SelectedServicesLab2Lab = null;
                        }

                        unitOfWork.VisitServiceServices.Add(new VisitService()
                        {
                            VisitId = model.Visit.VisitId,
                            ServiceId = item.SelectedServices,
                            ServiceSerial = numerForServiceInVisit + 1,
                            ServiceDate = DateTime.Now,
                            Lab2lab = item.SelectedServicesLab2Lab,
                        });

                        totalcost += unitOfWork.servicesPricelistService.GetById(item.SelectedServices).ServicePrice;
                        unitOfWork.Save();

                        var serviceStendRefid = unitOfWork._Context.ServicesPricelists.FirstOrDefault(x => x.ServiceId == item.SelectedServices).StandRef;
                        var isPackage = unitOfWork._Context.StandardServices.FirstOrDefault(x => x.ServiceId == serviceStendRefid).IsPackage;

                        #region case of package service
                        //if (serviceStendRefid != null && isPackage)
                        //{
                        //	var package = unitOfWork._Context.StandardServices.Include(x => x.Packages).FirstOrDefault(x => x.ServiceId == serviceStendRefid);

                        //	foreach (var service in package.Packages)
                        //	{
                        //		CreateBarcode(model.Visit.VisitId, service.ServiceId, serviceStendRefid);

                        //	}
                        //}
                        //else
                        //{
                        //	// Generate the barcode and save it
                        //	CreateBarcode(model.Visit.VisitId, item.SelectedServices);
                        //}


                        ////case of package service
                        //if (serviceStendRefid != null && isPackage)
                        //{
                        //    var package = unitOfWork._Context.ServicesPricelists.Include(x => x.Services).FirstOrDefault(x => x.ServiceId == item.SelectedServices);

                        //    foreach (var service in package.Services)
                        //    {
                        //        CreateBarcode(model.Visit.VisitId, service.ServiceId, package.ServiceId);

                        //    }
                        //}
                        //else
                        //{
                        //    // Generate the barcode and save it
                        //    CreateBarcode(model.Visit.VisitId, item.SelectedServices);
                        //}
                        #endregion

                        CreateBarcode(model.Visit.VisitId, item.SelectedServices);


                    }
                }

                // Add in invoice
                PatientInvoice patientInvoice = new PatientInvoice();
                patientInvoice.CreationDate = DateTime.Now;
                patientInvoice.InvoiceCost = totalcost;
                patientInvoice.Currency = "EGP";
                patientInvoice.PaymentType = "Cash";
                patientInvoice.VisitId = model.Visit.VisitId;
                patientInvoice.InvoiceStatus = "P";
                patientInvoice.LastUpdateBy = "ay7aga";
                patientInvoice.LastUpdateFrom = "2";
                patientInvoice.LastUpdateDate = DateTime.Now;
                patientInvoice.IsSupply = false;
                unitOfWork._Context.Add(patientInvoice);
                unitOfWork.Save();

                // Add in invoice details
                foreach (var item in model.VisitserviceViewModel)
                {
                    PatientInvoiceDetail invoiceDetail = new PatientInvoiceDetail();
                    invoiceDetail.InvId = patientInvoice.InvoiceId;
                    invoiceDetail.VisitId = patientInvoice.VisitId;
                    invoiceDetail.ServiceId = item.SelectedServices;
                    invoiceDetail.ServiceCost = unitOfWork.servicesPricelistService.GetById(item.SelectedServices).ServicePrice;
                    invoiceDetail.Serial = unitOfWork.VisitServiceServices.GetByServiceIdAndVisitId(item.SelectedServices, model.Visit.VisitId).Count + 1;
                    invoiceDetail.LastUpdateBy = "abdo";
                    invoiceDetail.LastUpdateFrom = ":::1";
                    invoiceDetail.LastUpdateDate = DateTime.Now;
                    unitOfWork._Context.Add(invoiceDetail);

Views/Visit/DetailServiceQrCode.cshtml
@{
}
<h1>hello</h1>
<img src="@ViewBag.QrCodeUri" class="img-thumbnail" />

Views/Visit/Details.cshtml
@using LAB.ViewModel;
@model VisitDetailsViewModel










<!--begin::Content-->
<div class="card flex-lg-row-fluid me-xl-18 mb-10 mb-xl-0 w-75 my-10 mx-20 p-10">
	<!--begin::Invoice 2 content-->
	<div class="mt-n1">
		<!--begin::Top-->
		<div class="d-flex flex-stack pb-10">
			
			<!-- begin::logo-->
			<div>
				<img src="~/Invoicelogo.png" width="150px" />
			</div>
			<!--end::Logo-->
			
		</div>
		<!--end::Top-->
		<!--begin::Wrapper-->
		<div class="m-0">
			<!--begin::Label-->
			<div class="fw-bold fs-3 text-gray-800 mb-8">@Model.Visit.Patient?.PatientName</div>
			<!--end::Label-->
			<!--begin::Row-->
			<div class="row g-5 mb-11">
				<!--end::Col-->
				<div class="col-sm-6">
					<!--end::Label-->
					<div class="fw-semibold fs-7 text-gray-600 mb-1">Visit Start Date:</div>
					<!--end::Label-->
					<!--end::Col-->
					<div class="fw-bold fs-6 text-gray-800">@Model.Visit.VisitStartDate</div>
					<!--end::Col-->
				</div>
			</div>
			<!--end::Row-->
			<!--begin::Card body-->
			<div class="card-body pt-0">
				<form asp-action="LogStatus" asp-controller="Visit">

					<input hidden name="visitId" value="@Model.Visit.VisitId" />

				<!--begin::Table-->
				<table class="table align-middle table-row-dashed fs-6 gy-5" id="kt_customers_table">
					<!--begin::Table head-->
					<thead>
						<!--begin::Table row-->
						<tr class="text-start text-gray-400 fw-bold fs-7 text-uppercase gs-0">
							<th class="min-w-125px">Service Name</th>	
							<th class="w-10px pe-2">
									<label>Collected:</label>
								<div class="form-check form-check-sm form-check-custom form-check-solid me-3">
									<input class="form-check-input " type="checkbox" data-kt-check="true" data-kt-check-target="#kt_customers_table .Collected" value="1" />
								</div>
							</th>
							<th class="w-10px pe-2">
								<label>Analisis:</label>
								<div class="form-check form-check-sm form-check-custom form-check-solid me-3">
								</div>
							</th>
							<th class="w-10px pe-2">
								<label>Completed:</label>
								<div class="form-check form-check-sm form-check-custom form-check-solid me-3">
								</div>
							</th>
							<th class="text-end min-w-70px">Actions</th>
						</tr>
						<!--end::Table row-->
					</thead>
					<!--end::Table head-->
					<!--begin::Table body-->

					<tbody class="fw-semibold text-gray-600">
							@for (int i=0; i< Model.Visit.ServiceBarcodes.Count ; i++)
							{
						<tr>
							<!--begin::Name=-->
							<td>
										
										<a href="#" class="text-gray-800 text-hover-primary mb-1">@Model.Visit.ServiceBarcodes.ElementAt(i).Services.ServiceName</a>
							</td>
							<!--end::Name=-->
							<!--begin::Checkbox-->
									@if (Model.Visit.ServiceBarcodes.ElementAt(i).SampleStatus == 3)
									{
								<td>
									<div class="form-check form-check-sm form-check-custom form-check-solid">
												<input class="form-check-input Collected" checked disabled name="isCollected" type="checkbox" value="@Model.Visit.ServiceBarcodes.ElementAt(i).BarcodeId" />
									</div>
								</td>
								<!--end::Checkbox-->
								<!--begin::Checkbox-->
								<td>
									<div class="form-check form-check-sm form-check-custom form-check-solid">
												<input class="form-check-input Analisis" checked disabled type="checkbox" name="isAnalisis" value="@Model.Visit.ServiceBarcodes.ElementAt(i).BarcodeId" />
									</div>
								</td>
								<!--end::Checkbox-->
								<!--begin::Checkbox-->
								<td>
									<div class="form-check form-check-sm form-check-custom form-check-solid">
												<input class="form-check-input Completed" checked disabled type="checkbox" name="isCompleted" value="@Model.Visit.ServiceBarcodes.ElementAt(i).BarcodeId" />
									</div>
								</td>

								}
									else if (Model.Visit.ServiceBarcodes.ElementAt(i).SampleStatus == 2)
								{
									<td>
										<div class="form-check form-check-sm form-check-custom form-check-solid">
												<input class="form-check-input Collected" name="isCollected" checked disabled type="checkbox" value="@Model.Visit.ServiceBarcodes.ElementAt(i).BarcodeId" />
										</div>
									</td>
									<!--end::Checkbox-->
									<!--begin::Checkbox-->
									<td>
										<div class="form-check form-check-sm form-check-custom form-check-solid">
												<input class="form-check-input Analisis" checked disabled type="checkbox" name="isAnalisis" value="@Model.Visit.ServiceBarcodes.ElementAt(i).BarcodeId" />
										</div>
									</td>
									<!--end::Checkbox-->
									<!--begin::Checkbox-->
									<td>
										<div class="form-check form-check-sm form-check-custom form-check-solid">
												<input class="form-check-input Completed" name="isCompleted" type="checkbox" value="@Model.Visit.ServiceBarcodes.ElementAt(i).BarcodeId" />
										</div>
									</td>
								}
									else if (Model.Visit.ServiceBarcodes.ElementAt(i).SampleStatus == 1)
								{
									<td>
										<div class="form-check form-check-sm form-check-custom form-check-solid">
												<input class="form-check-input Collected" checked disabled name="isCollected" type="checkbox" value="@Model.Visit.ServiceBarcodes.ElementAt(i).BarcodeId" />
										</div>
									</td>
									<!--end::Checkbox-->
									<!--begin::Checkbox-->
									<td>
										<div class="form-check form-check-sm form-check-custom form-check-solid">
												<input class="form-check-input Analisis"  type="checkbox" name="isAnalisis" value="@Model.Visit.ServiceBarcodes.ElementAt(i).BarcodeId" />
										</div>
									</td>
									<!--end::Checkbox-->
									<!--begin::Checkbox-->
									<td>
										<div class="form-check form-check-sm form-check-custom form-check-solid">
												<input class="form-check-input Completed" disabled type="checkbox" name="isCompleted" value="@Model.Visit.ServiceBarcodes.ElementAt(i).BarcodeId" />
										</div>
									</td>
								}
									else
								{
									<td>
										<div class="form-check form-check-sm form-check-custom form-check-solid">
												<input class="form-check-input Collected" name="isCollected" type="checkbox" value="@Model.Visit.ServiceBarcodes.ElementAt(i).BarcodeId" />
										</div>
									</td>
									<!--end::Checkbox-->
									<!--begin::Checkbox-->
									<td>
										<div class="form-check form-check-sm form-check-custom form-check-solid">
												<input class="form-check-input Analisis" name="isAnalisis" disabled type="checkbox" value="@Model.Visit.ServiceBarcodes.ElementAt(i).BarcodeId" />
										</div>
									</td>
									<!--end::Checkbox-->
									<!--begin::Checkbox-->
									<td>
										<div class="form-check form-check-sm form-check-custom form-check-solid">
												<input class="form-check-input Completed" name="isCompleted" disabled type="checkbox" value="@Model.Visit.ServiceBarcodes.ElementAt(i).BarcodeId" />
										</div>
									</td>
								}

							<!--end::Checkbox-->

							@{
								string hide = Model.Visit.ServiceBarcodes.ElementAt(i).SampleStatus != 3 ? "d-none" : "";
							}
						
						<!--begin::Action=-->
							<td class="text-end @hide">
								<a href="#" class="btn btn-sm btn-light btn-active-light-primary" data-kt-menu-trigger="click" data-kt-menu-placement="bottom-end">
									Actions
									<!--begin::Svg Icon | path: icons/duotune/arrows/arr072.svg-->
									<span class="svg-icon svg-icon-5 m-0">
										<svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
											<path d="M11.4343 12.7344L7.25 8.55005C6.83579 8.13583 6.16421 8.13584 5.75 8.55005C5.33579 8.96426 5.33579 9.63583 5.75 10.05L11.2929 15.5929C11.6834 15.9835 12.3166 15.9835 12.7071 15.5929L18.25 10.05C18.6642 9.63584 18.6642 8.96426 18.25 8.55005C17.8358 8.13584 17.1642 8.13584 16.75 8.55005L12.5657 12.7344C12.2533 13.0468 11.7467 13.0468 11.4343 12.7344Z" fill="currentColor" />
										</svg>
									</span>
									<!--end::Svg Icon-->
								</a>
								<!--begin::Menu-->
								<div class="menu menu-sub menu-sub-dropdown menu-column menu-rounded menu-gray-600 menu-state-bg-light-primary fw-semibold fs-7 w-125px py-4" data-kt-menu="true">
									<!--begin::Menu item-->
									<div class="menu-item px-3">

										<a asp-action="Generate" asp-controller="Report" asp-route-id="@Model.Visit.ServiceBarcodes.ElementAt(i).BarcodeId" class="menu-link px-3">Report</a>
									</div>
									<!--end::Menu item-->
					
								</div>
								<!--end::Menu-->
							</td>
							<!--end::Action=-->
						
						
						</tr>
						
						}
					</tbody>
					<!--end::Table body-->
				</table>
						<button type="submit" class="btn btn-primary">
							Save
						</button>
				<!--end::Table-->
					</form>
			</div>
			<!--end::Card body-->
		</div>
		<!--end::Wrapper-->
	</div>
	<!--end::Invoice 2 content-->
</div>
<!--end::Content-->

Views/Visit/ServiceVisit.cshtml
@model LAB.Models.Visit
@{
   // ViewData["Title"] = "ServiceVisit";
}


<div id="kt_app_content" class="app-content flex-column-fluid">
	<!--begin::Content container-->
	<div id="kt_app_content_container" class="app-container container-xxl">
		<!--begin::Card-->
		<div class="card">
			<!--begin::Card header-->
			<div class="card-header border-0 pt-6">
			
			<!--begin::Card body-->
			<div class="card-body pt-0">
				<!--begin::Table-->
				<div id="kt_customers_table_wrapper" class="dataTables_wrapper dt-bootstrap4 no-footer">
					<div class="table-responsive">
						<table class="table align-middle table-row-dashed fs-6 gy-5 dataTable no-footer" id="displayReportColumns">
							<!--begin::Table head-->
								<thead >
								<!--begin::Table row-->
								<tr  class="text-start text-gray-400 fw-bold fs-7 text-uppercase gs-0">

										<th  class="min-w-125px sorting text-dark " tabindex="0" aria-controls="kt_customers_table" rowspan="1" colspan="1" aria-label="Customer Name: activate to sort column ascending" style="width: 172.391px;">service</th>
										<th class="min-w-125px sorting text-dark " tabindex="0" aria-controls="kt_customers_table" rowspan="1" colspan="1" aria-label="Email: activate to sort column ascending" style="width: 213.356px;">Barcode</th>
										<th>
											<!-- Your existing table -->

											<a href="/Visit/PrintBarcodes?visitId=@Model.VisitId" class="btn btn-bg-success" id="printButton">Print Barcodes</a>
										</th>
										
							   </tr>
								<!--end::Table row-->
							</thead>
							<!--end::Table head-->
							<!--begin::Table body-->
							<tbody class="fw-semibold text-gray-600">
								@foreach (var item in Model.VisitServices)
								{
									<tr>
										<td>@item.Service.StandRefNavigation.ServiceName</td>
										<td>
											@{
												string visitId = item.VisitId.ToString(); // Convert to string
												string serviceId = item.ServiceId.ToString(); // Convert to string
												string imageUrl = $"/GeneratedBarcode/Service_{serviceId}/{visitId}_{serviceId}.png";
											}
											<img width="150px" src="@imageUrl" class="img-thumbnail">
										</td>
										<td></td>
									</tr>
								}
							

							</tbody>
							<!--end::Table body-->
						</table>
						<!--end::Table-->
					</div>
					<!--end::Card body-->
				</div>
			
			</div>
			<!--end::Content container-->

		</div>
	</div>
</div>
		
	<script src="~/plugins/custom/datatables/datatables.bundle.js"></script>
	<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>


	<script>
		$(document).ready(function () {
			var table = $("#displayReportColumns").DataTable({
				"aaSorting": [],
			});

			$('#SearchPatientWorklist').on('keyup', function () {
				table.search(this.value).draw();
			});

			// $("#printButton").on("click", function () {
			// 	$.ajax({
			// 		type: "POST",
			// 		url: "/Visit/PrintBarcodes?visitId=@Model.VisitId",
			// 		success: function (response) {
			// 			// This will open the PDF for printing in a new tab
			// 			// window.open(URL.createObjectURL(new Blob([response]))
			// 		}
			// 	});
			// });
		});
	</script>

Views/Visit/_ChangeServiceStatus.cshtml
@model VisitService
@{ Layout = null;}


<!--begin::Input group-->
<div class="fv-row mb-7">
	<!--begin::Label-->
	<label class="required fs-6 fw-semibold mb-2">Name</label>
	<!--end::Label-->
	<!--begin::Input-->
	<input type="text" class="form-control form-control-solid" disabled asp-for="Service.ServiceName" />
	<!--end::Input-->
</div>
<!--end::Input group-->

<!--begin::Input group-->
<div class="fv-row mb-7">
	<!--begin::Label-->
	<label class="required fs-6 fw-semibold mb-2">Name</label>
	
	<input type="text" class="form-control form-control-solid" disabled asp-for="Service.ServiceName" />
	<!--end::Input-->
</div>
<!--end::Input group-->