Models/ServicesPricelist.cs
using System;
using System.Collections.Generic;

namespace LAB.Models;

public partial class ServicesPricelist
{
    public int ServiceId { get; set; }

    public string? ServiceName { get; set; }

    public string? ServiceNameAr { get; set; }

    public double ServicePrice { get; set; }

    public int ServiceCat { get; set; }

    public int ContractId { get; set; }

    public int? StandRef { get; set; }

    public string LastUpdateBy { get; set; } = null!;

    public string LastUpdateFrom { get; set; } = null!;

    public DateTime LastUpdateDate { get; set; }

    public virtual VendorContract Contract { get; set; } = null!;

    public virtual ICollection<PatientInvoiceDetail> PatientInvoiceDetails { get; set; } = new List<PatientInvoiceDetail>();

    public virtual ICollection<ServiceBarcode> ServiceBarcodes { get; set; } = new List<ServiceBarcode>();

    public virtual ServicesCategory ServiceCatNavigation { get; set; } = null!;

    public virtual StandardService? StandRefNavigation { get; set; }

    public virtual ICollection<VisitService> VisitServices { get; set; } = new List<VisitService>();

    public virtual ICollection<StandardService> Services { get; set; } = new List<StandardService>();
}

Controllers/ServicesPricelistController.cs
using LAB.IService;
using Microsoft.AspNetCore.Mvc;
using LAB.Service;
using LAB.Models;
using OfficeOpenXml;
using System.Text.RegularExpressions;
using LAB.ViewModel;

namespace LAB.Controllers
{
	public class ServicesPricelistController : Controller
	{
		private readonly IUnitOfWork _unitOfWork;
		public ServicesPricelistController(IUnitOfWork unitOfWork)
		{
			_unitOfWork = unitOfWork;
		}

		public IActionResult Index()
		{
			var model = _unitOfWork.servicesPricelistService.GetAll();

			return View(model);
		}
		[HttpGet]
		public IActionResult Add(int id)
		{
			ServicesPricelistViewModel model = new();

			model.ContractId = id;
			model.LastUpdateDate = DateTime.Now;
			model.LastUpdateFrom = "hr";
			model.LastUpdateBy = "hr";
			model.standardServices = _unitOfWork.StandardServices.GetAll().ToList();
			model.categories  = _unitOfWork._Context.ServicesCategories.ToList();
			return View("_AddServicePartialView",model);
		}
		[HttpPost]
		public IActionResult Add(int id, ServicesPricelistViewModel ServicesPricelist)
		{
			ServicesPricelist newPriceList = new ServicesPricelist();
			if (ModelState.IsValid)
			{
				newPriceList.ServiceName = ServicesPricelist.ServiceName;
				newPriceList.ServiceNameAr = ServicesPricelist.ServiceNameAr;
				newPriceList.ServicePrice = ServicesPricelist.ServicePrice;
				newPriceList.ServiceCat = ServicesPricelist.ServiceCat;
				newPriceList.ContractId = ServicesPricelist.ContractId;
				newPriceList.StandRef = ServicesPricelist.StandRef;
				newPriceList.LastUpdateBy = ServicesPricelist.LastUpdateBy;
				newPriceList.LastUpdateFrom = ServicesPricelist.LastUpdateFrom;
				newPriceList.LastUpdateDate = ServicesPricelist.LastUpdateDate;
				_unitOfWork.servicesPricelistService.Add(newPriceList);
				_unitOfWork.Save();
				return RedirectToAction("index","Vendor");
			}
			return View(newPriceList);
		}

		public IActionResult Details(int id)
		{
			var Details = _unitOfWork.servicesPricelistService.GetById(id);
			return View(Details);
		}

		public IActionResult ImportSPLfile()
		{
			return View();
		}

		[HttpPost]
		public IActionResult Upload(IFormFile file)
		{
			if (file != null && file.Length > 0)
			{

				using (var stream = file.OpenReadStream())
				{
					using (var package = new ExcelPackage(stream))
					{
						ExcelPackage.LicenseContext = LicenseContext.NonCommercial;
						var worksheet = package.Workbook.Worksheets[0];
						var rowCount = worksheet.Dimension.Rows;


						List<ServicesPricelist> serviceserror = new List<ServicesPricelist>();


						for (int row = 2; row <= rowCount; row++) // Changed loop condition
						{
							var regexname = "[A-Z]";


							var ServiceNamee = worksheet.Cells[row, 1].Value?.ToString(); // Use ?. to handle null values
							var ServiceNameArr = worksheet.Cells[row, 2].Value?.ToString();
							var ServicePricevalue = worksheet.Cells[row, 3].Value?.ToString();
							var ServiceCata = worksheet.Cells[row, 4].Value?.ToString();
							var ContractID = worksheet.Cells[row, 5].Value?.ToString();
							var StanderdRef = worksheet.Cells[row, 6].Value?.ToString();

							if (string.IsNullOrWhiteSpace(ServiceNamee) || Regex.IsMatch(ServiceNamee, regexname) ||
								string.IsNullOrWhiteSpace(ServiceNameArr) || Regex.IsMatch(ServiceNameArr, regexname) ||
								string.IsNullOrWhiteSpace(ServicePricevalue) ||
								string.IsNullOrWhiteSpace(ServiceCata) ||
								string.IsNullOrWhiteSpace(ContractID) || string.IsNullOrWhiteSpace(StanderdRef)
								)
							{
								// Handle missing or invalid data as needed
								serviceserror.Add(new ServicesPricelist()); // Skip this row and proceed to the next
							}
							if (serviceserror.Count > 0)
							{
								return View("ErrorInSPLFile", serviceserror);
							}

							// Now, parse the values
							if (
								!double.TryParse(ServicePricevalue, out double ServicePrice) ||
								!int.TryParse(ServiceCata, out int ServiceCat) ||
								!int.TryParse(ContractID, out int ContractId) ||
								!int.TryParse(StanderdRef, out int StanderdREF)

								)
							{
								// Handle parsing errors as needed
								continue; // Skip this row and proceed to the next
							}
							else
							{
								_unitOfWork.servicesPricelistService.Add(new ServicesPricelist
								{
									ServiceName = ServiceNamee,
									ServiceNameAr = ServiceNameArr,
									ServicePrice = ServicePrice,
									ServiceCat = ServiceCat,
									ContractId = ContractId,
									StandRef = StanderdREF,
									LastUpdateBy = "abdo tarek",
									 LastUpdateDate = DateTime.Now,
									 LastUpdateFrom = ":::1",
									 
								});
							}
						}

						_unitOfWork.Save();
					}

				}
			}
			return RedirectToAction("Index",controllerName:"Vendor");
		}


		[HttpGet]
		public IActionResult ShowService(int id) 
		{
			var model = _unitOfWork.servicesPricelistService.GetAllByContractId(id);
			ViewBag.contractID = id;
			return PartialView("_ShowAllServiceInContructPartialView", model);
		}

		[HttpGet]
		public IActionResult ShowServiceInVisit(int vendorId)
		{
			var contract = _unitOfWork.ContractService.GetLastValidContractByVendorId(vendorId);
			if (contract == null )
			{
				contract = new VendorContract();
			}
			var model = new SPLSelectListViewModel();
			var serviceIncontract = _unitOfWork.servicesPricelistService.GetAllByContractId(contract.ContractId).ToList();
			if (serviceIncontract != null)
				model.ServicesPricelists = serviceIncontract;
			else
				model.ServicesPricelists=new List<ServicesPricelist>();
			model.L2LVendor = _unitOfWork.VendorService.GetLab2LabVendor();
			return PartialView("_ShowSPLInVisit", model);
		}

	}
}

Views/ServicesPricelist/ErrorInSPLFile.cshtml
@model IEnumerable<LAB.Models.ServicesPricelist>



<table class="table table-bordered table-hover" style="border-color: red;">


        <thead>
          <tr>
            <th>ServiceName</th>
            <th>ServiceNameAr</th>
            <th>ServicePrice</th>
            <th>ServiceCat</th>
            <th>StandRef</th>
            <th>LastUpdateBy</th>
            <th>LastUpdateFrom</th>
            <th>LastUpdateDate</th>


        </tr>
        </thead>

        <tbody>

           @foreach (var item in Model)
    {
        <tr>
           
                <td>@item.ServiceName</td>
                <td>@item.ServiceNameAr</td>
                <td>@item.ServicePrice</td>
                <td>@item.ServiceCat</td>
                <td>@item.StandRef</td>
                <td>@item.LastUpdateBy</td>
                <td>@item.LastUpdateFrom</td>
                <td>@item.LastUpdateDate</td>
                
            

        </tr>
        
    }


        </tbody>

    
        <a asp-action="Vendor" asp-controller="index" class="btn btn-primary" style="text-decoration:none">Back to list</a>


    </table>

Views/ServicesPricelist/ImportSPLfile.cshtml
<form method="post" asp-action="Upload" asp-controller="ServicesPricelist" enctype="multipart/form-data">
    <div class="info2">

        @Html.AntiForgeryToken()


        <div class="file-upload">

            <button type="submit" id="submit" value="Upload" class="file-upload-btn form-control">Upload</button>
            <div class="image-upload-wrap">
                @*<input type="file" name="excelFile" />*@
                <input class="file-upload-input form-control" name="file" type='file' id="file" />
                <div class="drag-text">
                    <h3>Drag and drop a file or select add Image</h3>
                </div>


            </div>

        </div>





    </div>
</form>

Views/ServicesPricelist/_AddServicePartialView.cshtml
@using LAB.ViewModel

@model ServicesPricelistViewModel
@{
	Layout=null ;
}

<form class="form fv-plugins-bootstrap5 fv-plugins-framework" method="post" asp-controller="ServicesPricelist" asp-action="Add" >

	<!--begin::hidden info-->
	<input type="hidden" class="form-control form-control-solid" placeholder=""  asp-for="ServiceId">
	<input type="hidden" class="form-control form-control-solid" placeholder="" asp-for="ContractId">
	<input type="hidden" class="form-control form-control-solid" placeholder="" asp-for="LastUpdateBy">
	<input type="hidden" class="form-control form-control-solid" placeholder="" asp-for="LastUpdateDate">
	<input type="hidden" class="form-control form-control-solid" placeholder="" asp-for="LastUpdateFrom">




	
	<!--begin::Modal body-->
	<div class="modal-body py-10 px-lg-17">
		<!--begin::Scroll-->
		<div class="scroll-y me-n7 pe-7" id="kt_modal_add_customer_scroll" data-kt-scroll="true" data-kt-scroll-activate="{default: false, lg: true}" data-kt-scroll-max-height="auto" data-kt-scroll-dependencies="#kt_modal_add_customer_header" data-kt-scroll-wrappers="#kt_modal_add_customer_scroll" data-kt-scroll-offset="300px" style="max-height: 490px;">
			<!--begin::Input group-->
			<div class="fv-row mb-7 fv-plugins-icon-container">
				<!--begin::Label-->
				<label class="required fs-6 fw-semibold mb-2">Service Name</label>
				<!--end::Label-->
				<!--begin::Input-->
				<input type="text" class="form-control form-control-solid" placeholder="" asp-for="ServiceName">
				<!--end::Input-->
				<div class="fv-plugins-message-container invalid-feedback"></div>
			</div>
			<!--end::Input group-->
			<!--begin::Input group-->
			<div class="fv-row mb-7 fv-plugins-icon-container">
				<!--begin::Label-->
				<label class="required fs-6 fw-semibold mb-2">ServicePrice</label>
				<!--end::Label-->
				<!--begin::Input-->
				<input  class="form-control form-control-solid" placeholder="" asp-for="ServicePrice">
				<!--end::Input-->
				<div class="fv-plugins-message-container invalid-feedback"></div>
			</div>
			<!--end::Input group-->
			<!--begin::Input group-->
			<div class="fv-row mb-15">
				<!--begin::Label-->
				<label class="fs-6 fw-semibold mb-2">Service Category</label>
				<!--end::Label-->
				<!--begin::Input-->
				
				<select asp-for="ServiceCat" id="addrefdocSelect" class="form-select" data-control="select2" data-placeholder="Select Ctegory Service">
					<option></option>
					
					@foreach (var item in Model.categories)
					{

						<option value="@item.ServiceCatId">@item.ServiceCatName</option>
					}
				</select>
				
			
				<!--end::Input-->
			</div>
			<!--end::Input group-->
			<!--begin::Input group-->
			<div class="fv-row mb-15">
				<!--begin::Label-->
				<label class="fs-6 fw-semibold mb-2">Services</label>
				<!--end::Label-->
				<!--begin::Input-->

				<select asp-for="StandRef" id="addrefdocSelect" class="form-select" data-control="select2" data-placeholder="Select Ctegory Service">
					<option></option>

					@foreach (var item in Model.standardServices)
					{

						<option value="@item.ServiceId">@item.ServiceName</option>
					}
				</select>


				<!--end::Input-->
			</div>
			<!--end::Input group-->


		
	<!--begin::Modal footer-->
	<div class="modal-footer flex-center">
		<!--begin::Button-->
		<button type="reset" id="kt_modal_add_customer_cancel" class="btn btn-light me-3">Discard</button>
		<!--end::Button-->
		<!--begin::Button-->
		<button type="submit" class="btn btn-primary">
			<span class="indicator-label">Submit</span>
			<span class="indicator-progress">
				Please wait...
				<span class="spinner-border spinner-border-sm align-middle ms-2"></span>
			</span>
		</button>
		<!--end::Button-->
	</div>
		</div>
	</div>
	<!--end::Modal footer-->
</form>

Views/ServicesPricelist/_ShowAllServiceInContructPartialView.cshtml
@model List<ServicesPricelist>




<div class="card-header border-0">
	<h2 class="card-title fw-bold text-dark">Service Price List</h2>
</div>
<div class="card-header border-0">
	<div class="d-flex justify-content-end" data-kt-customer-table-toolbar="base">

		<!--Add & import & Export service -->
		<button type="button" class="btn btn-primary  h-40px w-80px mx-3" data-bs-toggle="modal" onclick="loadPartial('/ServicesPricelist/Add/@ViewBag.contractID', 'AddSPLForm')" data-bs-target="#kt_modal_new_Contact">Add Service</button>

		<a asp-action="ImportSPLfile" asp-controller="ServicesPricelist" class="btn btn-light-primary h-40px">
			import
		</a>

		<!--begin::Export-->
		<button type="button" class="btn  h-40px btn-light-primary me-3" onclick="exportToExcel()">
			<!--begin::Svg Icon | path: icons/duotune/arrows/arr078.svg-->
			<span class="svg-icon svg-icon-2">
				<svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
					<rect opacity="0.3" x="12.75" y="4.25" width="12" height="2" rx="1" transform="rotate(90 12.75 4.25)" fill="currentColor" />
					<path d="M12.0573 6.11875L13.5203 7.87435C13.9121 8.34457 14.6232 8.37683 15.056 7.94401C15.4457 7.5543 15.4641 6.92836 15.0979 6.51643L12.4974 3.59084C12.0996 3.14332 11.4004 3.14332 11.0026 3.59084L8.40206 6.51643C8.0359 6.92836 8.0543 7.5543 8.44401 7.94401C8.87683 8.37683 9.58785 8.34458 9.9797 7.87435L11.4427 6.11875C11.6026 5.92684 11.8974 5.92684 12.0573 6.11875Z" fill="currentColor" />
					<path opacity="0.3" d="M18.75 8.25H17.75C17.1977 8.25 16.75 8.69772 16.75 9.25C16.75 9.80228 17.1977 10.25 17.75 10.25C18.3023 10.25 18.75 10.6977 18.75 11.25V18.25C18.75 18.8023 18.3023 19.25 17.75 19.25H5.75C5.19772 19.25 4.75 18.8023 4.75 18.25V11.25C4.75 10.6977 5.19771 10.25 5.75 10.25C6.30229 10.25 6.75 9.80228 6.75 9.25C6.75 8.69772 6.30229 8.25 5.75 8.25H4.75C3.64543 8.25 2.75 9.14543 2.75 10.25V19.25C2.75 20.3546 3.64543 21.25 4.75 21.25H18.75C19.8546 21.25 20.75 20.3546 20.75 19.25V10.25C20.75 9.14543 19.8546 8.25 18.75 8.25Z" fill="currentColor" />
				</svg>
			</span>
			<!--end::Svg Icon-->Export
		</button>

		<!--end::Export-->
	</div>
</div>
<!--end::Header-->
<div class="card-body pt-2">
  <div class="row">
	<div class="d-flex align-items-center position-relative my-1">
		<!--begin::Svg Icon | path: icons/duotune/general/gen021.svg-->
		<span class="svg-icon svg-icon-1 position-absolute ms-6">
			<svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
				<rect opacity="0.5" x="17.0365" y="15.1223" width="8.15546" height="2" rx="1" transform="rotate(45 17.0365 15.1223)" fill="currentColor"></rect>
				<path d="M11 19C6.55556 19 3 15.4444 3 11C3 6.55556 6.55556 3 11 3C15.4444 3 19 6.55556 19 11C19 15.4444 15.4444 19 11 19ZM11 5C7.53333 5 5 7.53333 5 11C5 14.4667 7.53333 17 11 17C14.4667 17 17 14.4667 17 11C17 7.53333 14.4667 5 11 5Z" fill="currentColor"></path>
			</svg>
		</span>
		<!--end::Svg Icon-->
		<input id="SearchServicePriceList" type="text" data-kt-customer-table-filter="search" class="form-control form-control-solid w-250px ps-15" placeholder="Search For ">
	</div>
 </div>


	<table class="table align-middle table-row-dashed fs-6 gy-5" id="displaySevice">
		<thead>
			<tr>

				<th>
					Service Name
				</th>
			</tr>
		</thead>
		<tbody>
			@if (Model.Count>0)
			{
			@foreach (var item in Model)
			{
				<tr class="w-100">

					<td class="w-50px">
						<!--begin::Item-->
						<div class="d-flex align-items-center">
							<!--begin::Bullet-->
							<span class="bullet bullet-vertical h-40px bg-success"></span>
							<!--end::Bullet-->
							<!--begin::Description-->
							<div class="flex-grow-1 ms-2">
								<a href="#" class="text-gray-800 text-hover-primary fw-bold fs-6"> @item.ServiceName  </a>
								<span class="text-muted fw-semibold d-block">  @item.ServicePrice  </span>
							</div>
							<!--end::Description-->
							<span class="badge badge-light-success fs-8 fw-bold">New</span>
						</div>
						<!--end:Item-->
					</td>
				</tr>
			}
		}else
		{
			<tr class="w-100">

				<td class="w-50px">
					<h1>No Data</h1>
				</td>
			</tr>
		}
		</tbody>
	</table>
</div>
	<script src="~/plugins/custom/datatables/datatables.bundle.js"></script>
	<script>
	$('#SearchServicePriceList').on('keyup', function () {
		table.search(this.value).draw();

	});

	var table = $("#displaySevice").DataTable({
		"aaSorting": [],

	});
	</script>

Views/ServicesPricelist/_ShowSPLInVisit.cshtml
@using LAB.ViewModel;
@model SPLSelectListViewModel
@{
    Layout = null;
}
<div class="d-flex flex-column gap-10">
	<!--begin::Input group-->
	<div>
		<!--begin::Label-->
		<label class="form-label">Add Services to this Visit</label>
		<!--end::Label-->
		<!--begin::Selected products-->
		<div class="row row-cols-1 row-cols-xl-3 row-cols-md-2 border border-dashed rounded pt-3 pb-1 px-2 mb-5 mh-300px overflow-scroll" id="kt_ecommerce_edit_order_selected_products">
			<!--begin::Empty message-->
			<span class="w-100 text-muted">Select one or more Service from the list below by ticking the checkbox.</span>
			<!--end::Empty message-->
		</div>
		<!--begin::Selected products-->
		<!--begin::Total price-->
		<div class="fw-bold fs-4">
			Total Cost: $
			<span id="kt_ecommerce_edit_order_total_price">0.00</span>
		</div>
		<!--end::Total price-->
	</div>
	<!--end::Input group-->
	<!--begin::Separator-->
	<div class="separator"></div>
	<!--end::Separator-->
	<!--begin::Search products-->
	<div class="d-flex align-items-center position-relative mb-n7">
		<!--begin::Svg Icon | path: icons/duotune/general/gen021.svg-->
		<span class="svg-icon svg-icon-1 position-absolute ms-4">
			<svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
				<rect opacity="0.5" x="17.0365" y="15.1223" width="8.15546" height="2" rx="1" transform="rotate(45 17.0365 15.1223)" fill="currentColor" />
				<path d="M11 19C6.55556 19 3 15.4444 3 11C3 6.55556 6.55556 3 11 3C15.4444 3 19 6.55556 19 11C19 15.4444 15.4444 19 11 19ZM11 5C7.53333 5 5 7.53333 5 11C5 14.4667 7.53333 17 11 17C14.4667 17 17 14.4667 17 11C17 7.53333 14.4667 5 11 5Z" fill="currentColor" />
			</svg>
		</span>
		<!--end::Svg Icon-->
		<input type="text" data-kt-ecommerce-edit-order-filter="search" class="form-control form-control-solid w-100 w-lg-50 ps-14" placeholder="Search Products" />
	</div>
	<!--end::Search products-->
	<!--begin::Table-->
	<table class="table align-middle table-row-dashed fs-6 gy-5" id="kt_ecommerce_edit_order_product_table">
		<!--begin::Table head-->
		<thead>
			<tr class="text-start text-gray-400 fw-bold fs-7 text-uppercase gs-0">
				<th class="w-25px pe-2"></th>
				<th class="min-w-200px">Service</th>
				<th class="min-w-150px">Lab to Lab</th>
				<th class="min-w-100px text-end pe-5">Discount</th>
			</tr>
		</thead>
		<!--end::Table head-->
		<!--begin::Table body-->
		<tbody class="fw-semibold text-gray-600">
			<!--begin::Table row-->
			@for (int i = 0; i < Model.ServicesPricelists.Count; i++)
			{

				<tr>
					<!--begin::Checkbox-->
					<td>
						<div class="form-check form-check-sm form-check-custom form-check-solid">
							<input class="form-check-input SelectedServices" name="selecSelectedServices" type="checkbox" value="@Model.ServicesPricelists[i].ServiceId" />

						</div>

					</td>
					<!--end::Checkbox-->
					<!--begin::Product=-->
					<td>
						<div class="d-flex align-items-center" data-kt-ecommerce-edit-order-filter="product" data-kt-ecommerce-edit-order-id="product_1">
							<!--begin::Thumbnail-->
							<a class="symbol symbol-50px">

							</a>
							<!--end::Thumbnail-->
							<div class="ms-5">
								<!--begin::Title-->
								<a class="text-gray-800 text-hover-primary fs-5 fw-bold">@Model.ServicesPricelists[@i].ServiceName</a>
								<!--end::Title-->
								<!--begin::Price-->
								<div class="fw-semibold fs-7">
									Price: $
									<span data-kt-ecommerce-edit-order-filter="price">@Model.ServicesPricelists[@i].ServicePrice</span>
								</div>
								<!--end::Price-->
								<!--begin::SKU-->
								<div class="text-muted fs-7">SKU: 04953004</div>
								<!--end::SKU-->
							</div>
						</div>
					</td>
					<!--end::Product=-->
					<td>
						<select disabled name="SelectedServicesLab2Lab" data-control="select2" data-placeholder="Select Lab" class="form-control SelectedServicesLab2Lab">
							<option value="0">Select Lab</option>
							@foreach (var vendor in Model.L2LVendor)
							{
								<option value="@vendor.VendorId">@vendor.VendorName</option>
							}
						</select>
					</td>
					<!--begin: Discount=-->
					<td class="text-end pe-5" data-order="28">
						<input disabled class="form-control SelectedServicesDiscount" type="number" value="0" min="0" max="100" name="SelectedServicesDiscount">
					</td>
					<!--end: Discount=-->
				</tr>
			}

		</tbody>
		<!--end::Table body-->
	</table>
	<!--end::Table-->
</div>
									
<script src="~/js/custom/apps/ecommerce/sales/save-order.js"></script>

<script>


	// Select checkboxes with a class starting with 'SelectedServices'
	$("input[class^='form-check-input SelectedServices']").change(function () {
		var $row = $(this).closest("tr");
		var $select = $row.find("select[class^='form-control SelectedServicesLab2Lab']");
		var $input = $row.find("input[class^='form-control SelectedServicesDiscount']");

		if (this.checked) {
			$select.prop("disabled", false);
			$input.prop("disabled", false);
		} else {
			$select.prop("disabled", true).val(0);
			$input.prop("disabled", true).val('');
		}
	});

</script>